apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: testing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: nginx
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
            requests: 
              memory: "200Mi"
              cpu: "200m"
